### ISSUE TITLE
Package latest release to H2MigrationTool-all.jar artifact

### ISSUE THREAD

**Issue by dlmcpaul** [manticore-projects/H2MigrationTool#11]
The 1.3 and 1.4 releases don't have the 2 packaged jar available as downloads (eg H2MigrationTool-all.jar).

It would be good if you could add them as it simplifies using the tool in scripts.

**Comment by manticore-projects** [comment]
Greetings,

You can download from here: https://manticore-projects.com/H2MigrationTool/index.html

**Comment by dlmcpaul** [comment]
Thank you.  Sorry for the noise.

**Comment by manticore-projects** [comment]
You are most welcome! Just ask if there is any question or concern. Cheers
