### ISSUE TITLE
Artifact is not on Maven Central

### ISSUE THREAD

**Issue by tchemit** [manticore-projects/H2MigrationTool#12]
Can you fix this please ?

Many thanks.

**Comment by manticore-projects** [comment]
Greetings!

Thank you for your report, but please elaborate on your challenge:

1) you can download from here https://manticore-projects.com/H2MigrationTool/index.html
2) you can find the Maven Artifact here: https://mvnrepository.com/artifact/com.manticore-projects.tools/h2migrationtool/1.4

What is missing please?

**Comment by tchemit** [comment]
In your documentation it says **H**2MigrationTool, but should be **h**2MigrationTool

**Comment by tchemit** [comment]
```
<dependency>
    <groupId>com.manticore-projects.tools</groupId>
    <artifactId>h2migrationtool</artifactId>
    <version>1.4</version>
</dependency>
```

**Comment by manticore-projects** [comment]
Thank you for the hint, I would correct that of course!

**Comment by tchemit** [comment]
you are welcome

**Comment by manticore-projects** [comment]
Fixed, I also made the Maven Badges clickable.
Thanks again and cheers!
