### ISSUE TITLE
Missing Main Class in Manifest Files

### ISSUE THREAD

**Issue by precoder** [manticore-projects/H2MigrationTool#14]
Hello,

Thank you very much for a nice tool to migrate H2 Databases.

I have seen that the JAR files are uploaded into Maven Central:
https://mvnrepository.com/artifact/com.manticore-projects.tools/h2migrationtool/1.4

However when I try to execute the file with -jar :
```
C:\Downloads>java -jar h2migrationtool-1.4.jar
no main manifest attribute, in h2migrationtool-1.4.jar
```

Then I tried with -cp then I also get another error:
```
C:\Downloads>java -cp h2migrationtool-1.4.jar com.manticore.h2.H2MigrationTool
Error: Unable to initialize main class com.manticore.h2.H2MigrationTool
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
```

It seems like JAR files uploaded into Maven are somehow not working. Manifest files are all empty:
`Manifest-Version: 1.0`

I have found another JAR in the Web Site and it works with java -jar:
http://manticore-projects.com/download/H2MigrationTool-1.4/H2MigrationTool-1.4-all.jar

and it has correct manifest:
`Manifest-Version: 1.0
Main-Class: com.manticore.h2.H2MigrationTool
`

Actually this 1.4 version is not listed on your Web Page, I guessed the link by existing other link for 1.3.7:
https://manticore-projects.com/H2MigrationTool/index.html

Do you plan to update the Web Site and also artifacts in Maven?

**Comment by manticore-projects** [comment]
Greetings!

The Maven Repo really points on the slim package only and does not contain the 3rd part libs.
If you want to run as standalone you will need to use the UEBER Jar from the WebSite (or build from source).

Although I would double check on the versioning stable vs snapshot.

**Comment by precoder** [comment]
Thank you very much for quick response and information, I would probably use the Version from the Website :)
