### ISSUE TITLE
CLI creates migrated file name with null appended

### ISSUE THREAD

**Issue by precoder** [manticore-projects/H2MigrationTool#15]
Hello,

I am using the JAR file from:
http://manticore-projects.com/download/H2MigrationTool-1.4/H2MigrationTool-1.4-all.jar

My initial H2 Database filename is items.mv.db
I am trying to migrate the Database from 1.4.196 to 2.2.229

When I migrate the H2 Database with the GUI, as the final file name I get:
items.mv.db.229.mv.db

If I use the Command Line tool with following parameters:
`C:\Downloads>java -jar H2MigrationTool-1.4-all.jar --user=user --password=password --version-from=1.4.196 --version-to=2.2.229 --db-file=C:\Downloads\items.mv.db --compression=ZIP --options=QUIRKS_MODE --force`

then as result I get:
items.mv.db.229null.mv.db

Seems like somewhre a null string is appended into final filename, it is not a big issue but would be nice if both GUI and CLI gives the same results. If GUI can write the parameters into console, then it would be easier to find the corresponding CLI parameters.

Here the CLI part calls migrate tool with null connection parameters:
https://github.com/manticore-projects/H2MigrationTool/blob/master/src/main/java/com/manticore/h2/H2MigrationTool.java#L553

Then this null parameter used in the connection JDBC String without checking for null, which seems like causes the "null" value in the final filename:
https://github.com/manticore-projects/H2MigrationTool/blob/master/src/main/java/com/manticore/h2/H2MigrationTool.java#L775

**Comment by manticore-projects** [comment]
Thank you for reporting.
To be honest, I have been too lazy to use the CLI since the UI was most convenient and I failed to remember the syntax. 

I will work on it and give it some love.

**Comment by manticore-projects** [comment]
Thanks again for reporting, I think I've gotten this fixed:
```text
are@ryzen ~/D/s/H/b/distributions (master)> java -jar H2MigrationTool-shadow-1.4.0-SNAPSHOT/lib/H2MigrationTool-1.4.0-SNAPSHOT-all.jar -t 2.2.229 -f 2.2.229 -d /home/are/.manticore/ifrsbox.mv.db --force
[0.012s][warning][cds] This file is not the one used while building the shared archive file: /usr/lib/jvm/java-21-jetbrains/lib/modules
[0.012s][warning][cds] This file is not the one used while building the shared archive file: /usr/lib/jvm/java-21-jetbrains/lib/modules
[0.012s][warning][cds] /usr/lib/jvm/java-21-jetbrains/lib/modules size has changed.
Mar 09, 2024 11:07:33 AM com.manticore.h2.H2MigrationTool migrate
INFO: Found H2 DB /home/are/.manticore/ifrsbox which will be exported to SQL Script
Mar 09, 2024 11:07:33 AM com.manticore.h2.H2MigrationTool migrate
INFO: Wrote H2-2.2.229 database to script: /home/are/.manticore/ifrsbox.sql
Mar 09, 2024 11:07:34 AM com.manticore.h2.H2MigrationTool migrate
INFO: Created new H2-2.2.229 database: /home/are/.manticore/ifrsbox.229.mv.db
```

And also works with SQL file
```
are@ryzen ~/D/s/H/b/distributions (master)> java -jar H2MigrationTool-shadow-1.4.0-SNAPSHOT/lib/H2MigrationTool-1.4.0-SNAPSHOT-all.jar -t 2.2.229 -f 2.2.229 -d /home/are/.manticore/ifrsbox.sql --force
[0.010s][warning][cds] This file is not the one used while building the shared archive file: /usr/lib/jvm/java-21-jetbrains/lib/modules
[0.010s][warning][cds] This file is not the one used while building the shared archive file: /usr/lib/jvm/java-21-jetbrains/lib/modules
[0.010s][warning][cds] /usr/lib/jvm/java-21-jetbrains/lib/modules size has changed.
Mar 09, 2024 11:08:57 AM com.manticore.h2.H2MigrationTool migrate
INFO: Found SQL Script /home/are/.manticore/ifrsbox.sql which will be imported directly.
Mar 09, 2024 11:08:59 AM com.manticore.h2.H2MigrationTool migrate
INFO: Created new H2-2.2.229 database: /home/are/.manticore/ifrsbox.229.mv.db
```
