### ISSUE TITLE
Recover a corrupted H2 DB - is it also possible ?

### ISSUE THREAD

**Issue by osenbg** [manticore-projects/H2MigrationTool#2]
Hi,

I think your MigrationTool is a good Base to also simply recover corrupted H2 DB's.
Do you plan to extend it?

regards

Stefan

**Comment by manticore-projects** [comment]
Thank you for the excellent idea, I will look into this.

**Comment by manticore-projects** [comment]
Solved via f41a413e54b27aa9ab4cff4c5ae38b7ce6585fe7

**Comment by osenbg** [comment]
Hi Andreas,

is it possible to start recover with  the CLI-Interface? 
The GUI is nice but i think the main "real use" is CLI 

Stefan

**Comment by manticore-projects** [comment]
Sure! Unfortunately I really rushed the implementation between my first and second coffee today and did not pay much attention to the details. I will complete as soon as electricity comes back.Thanks for the feedback on the CLI. I did not know that it was of interest for anyone. Will care more about it from now on.Greetings from Thailand!Sent from my Galaxy
-------- Original message --------From: osenbg ***@***.***> Date: 04/06/2021  13:30  (GMT+07:00) To: manticore-projects/H2MigrationTool ***@***.***> Cc: manticore-projects ***@***.***>, State change ***@***.***> Subject: Re: [manticore-projects/H2MigrationTool] Recover a corrupted H2 DB -
  is it also possible ? (#2) 
Hi Andreas,
is it possible to start recover with  the CLI-Interface?
The GUI is nice but i think the main "real use" is CLI
Stefan

**Comment by osenbg** [comment]
absolutely, i think the main Interface to use it is CLI (not GUI). 

Stefan

**Comment by manticore-projects** [comment]
Fixed via 6f5b88a87e644cc8f41246d38e4dc4618d301615 although that was sewed with a very hot needle just to get the cow off the ice. (I love German proverbs which make no sense in any other language.)

Cheers.
