### ISSUE TITLE
Release 1.6

### ISSUE THREAD

**Issue by glaplace** [manticore-projects/H2MigrationTool#20]
hello,

Have you already planned the next release ? 
Will it be available on the central maven repositories?

Thanks in advance.

**Comment by manticore-projects** [comment]
Typically we release when H2 Database has released a new version.
Since this happens only once in a decade or so we can release 1.6 now. However it hold no actual benefit and I'd recommend to go with the Snapshots and to understand our software as "rolling releases".

**Comment by glaplace** [comment]
Hello,

I use H2MigrationTool as a library.
A frozen version seems more sustainable over time, in my case.
This release would allow me to make the build more reliable.

I am aware that this is not necessarily the purpose of the tool intended to be used with the GUI.

Thanks in advance.

**Comment by manticore-projects** [comment]
No problem, I will pack a release latest tomorrow.

**Comment by manticore-projects** [comment]
Should be sorted out, pending updates of the website.

![image](https://github.com/manticore-projects/H2MigrationTool/assets/18080123/2ee4f343-d8db-47b8-9419-19243ef0736d)
