### ISSUE TITLE
Recovery did not work - CLI with Nullpointer 

### ISSUE THREAD

**Issue by osenbg** [manticore-projects/H2MigrationTool#3]
Hi Andreas,

i had no luck because of this:

`java -jar H2MigrationTool.jar com.manticore.Recovery -f 1.3.176 -d zws2-lite.h2.db
Juni 05, 2021 1:11:01 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: /drivers
Juni 05, 2021 1:11:01 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: Found H2 library h2-1.3.176.jar
Juni 05, 2021 1:11:01 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: H2-1.3.176
Juni 05, 2021 1:11:01 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: Found H2 library h2-1.4.199.jar
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: H2-1.4.199
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: Found H2 library h2-1.4.200.jar
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: H2-1.4.200
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: Found H2 library h2-2.0.201-0616da1b8.jar
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: H2-2.0.201-0616da1b8
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: Found H2 library h2-2.0.201-212cb2cfe.jar
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: H2-2.0.201-212cb2cfe
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: Found H2 library h2-2.0.201-281898bce.jar
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: H2-2.0.201-281898bce
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: Found H2 library h2-2.0.201-2c7cb8658.jar
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: H2-2.0.201-2c7cb8658
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: Found H2 library h2-2.0.201-34c42e526.jar
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: H2-2.0.201-34c42e526
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: Found H2 library h2-2.0.201-6e4746589.jar
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: H2-2.0.201-6e4746589
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: Found H2 library h2-2.0.201-888e2284f-dirty.jar
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: H2-2.0.201-888e2284f
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: Found H2 library h2-2.0.201-8c03d6c4a.jar
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: H2-2.0.201-8c03d6c4a
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: Found H2 library h2-2.0.201.jar
Juni 05, 2021 1:11:02 NACHM. com.manticore.h2.H2MigrationTool readDriverRecords
INFORMATION: H2-2.0.201
Exception in thread "main" java.lang.Exception: Failed to migrate the database.
	at com.manticore.h2.H2MigrationTool.main(H2MigrationTool.java:1144)
Caused by: java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
	at com.manticore.h2.H2MigrationTool.getDriverRecord(H2MigrationTool.java:592)
	at com.manticore.h2.H2MigrationTool.getDriverRecord(H2MigrationTool.java:626)
	at com.manticore.h2.H2MigrationTool.migrate(H2MigrationTool.java:835)
	at com.manticore.h2.H2MigrationTool.main(H2MigrationTool.java:1137)
`

**Comment by manticore-projects** [comment]
Thank you for your feedback.

On Sat, 2021-06-05 at 04:14 -0700, osenbg wrote:
> java -jar H2MigrationTool.jar com.manticore.Recovery -f 1.3.176 -d
> zws2-lite.h2.db


This call does not look right to me. It is not supposed to be

java -cp H2MigrationTool.jar com.manticore.Recovery -f 1.3.176 -d zws2-
lite.h2.db

(Although I agree that I will need to consider such use cases and
respond more gracefully.)

Best regards
Andreas

**Comment by osenbg** [comment]
Hi Andreas, 

sorry you are right. 
But isn't ist better to make recovery as an option for the CLI and not a separate command ?

Stefan

**Comment by manticore-projects** [comment]
> sorry you are right.
Not a problem at all.
Did it work for you eventually?

> But isn't ist better to make recovery as an option for the CLI and not a separate command ?

I am very much undecided about that and would like to ask you for contributing your ideas. I see the following possibilities:

1) Split into different Commands/Classes

- similar to `git pull ...` `git push ...` and friends, although this is heavily spoiled by the clumsy `java -cp ...` syntax
The main advantage of this approach is a clean separation of the CLI because a lot of the CLI Options apply only to `MIGRATE` but not to `RECOVER`

2) keep everything in one Command/Class and introduce another CLI Option `--command=RECOVER`
- this would solve the Classpath/JAR confusion but adds complexity to the CLI Options, which are fairly complex for the Migration tool already

3) Wrap everything with 2 shell scripts `RECOVER.sh` and `MIGRATE.sh`
- problem is, that such scripts are OS dependent and also rely more or less on JAVA_HOME being set correctly

We can actually combine all 3 ways together, but please let me know first which way you would like to prefer and how you would like to call `RECOVER`. (I never used RECOVER for myself and am more focused on the `MIGRATE` to work smooth.)


Looking forward to hear from you, Cheers
Andreas

**Comment by osenbg** [comment]
Hi Andreas,

i think option "1" is the way you should go.

greatings from Germany 

Stefan

**Comment by manticore-projects** [comment]
Stale.
