### ISSUE TITLE
Java version (class file version 55.0)

### ISSUE THREAD

**Issue by goranschwarz** [manticore-projects/H2MigrationTool#5]
Is there a reason why the JAR file are compiled with Java 11 (class file version 55.0)
H2 itself, can use Java 8
If there are no reason (just a mistake), then can it please be compiled with Java 8, which makes migration easier! (if there OS only have java 8 installed)

**Comment by manticore-projects** [comment]
Greetings, 

we indeed depend on Java 11 now since most of the build and QA/CI tools are Java 11. However [you can try the tool online here.](https://h2migrationtool.manticore-projects.com) without installing a JRE 11.

**Comment by manticore-projects** [comment]
Closing this, since no further questions have been asked.
