### ISSUE TITLE
In new release missed 1.4.196 H2 version

### ISSUE THREAD

**Issue by JavaOPs** [manticore-projects/H2MigrationTool#6]

**Comment by JavaOPs** [comment]
In new release missed 1.4.196 H2 version 
![image](https://user-images.githubusercontent.com/13649199/168479609-44b432c7-ef23-423e-89dd-74e7ac3cb9f2.png)

**Comment by manticore-projects** [comment]
That's correct, but you can always add ANY OTHER H2 Jar (right side, click on `+`).
